### ISSUE TITLE
Node does not exists

### ISSUE THREAD

**Issue by viklen30** [daxcay/ComfyUI-TG#3]
I'm trying to change the text, it's not working.
![Без имени-1](https://github.com/user-attachments/assets/01f71928-e755-4389-8fc3-0b6e0db48720)
![Снимок экрана_26-9-2024_134841_127 0 0 1](https://github.com/user-attachments/assets/8621b8cf-6fb9-4b41-8311-ea89a3fcdc4c)

**Comment by viklen30** [comment]
sorry im dumb  /s 240 0 ........   :)

**Comment by daxcay** [comment]
@viklen30 hi i will in future try to make commands simple i guess. it has a bit of learning curve. but i think we remember numbers better so a number will be fast in compared to test. ?
